package types

// Source: bcrypt.h
const (
	BCRYPT_OPAQUE_KEY_BLOB_TYPE   = "OpaqueKeyBlob"
	BCRYPT_KEY_DATA_BLOB_TYPE     = "KeyDataBlob"
	BCRYPT_AES_WRAP_KEY_BLOB_TYPE = "Rfc3565KeyWrapBlob"
	BCRYPT_ECCPUBLIC_BLOB_TYPE    = "ECCPUBLICBLOB"
	BCRYPT_ECCPRIVATE_BLOB_TYPE   = "ECCPRIVATEBLOB"
	BCRYPT_RSA_PUBLIC_BLOB_TYPE    = "RSAPUBLICBLOB"
	BCRYPT_RSA_PRIVATE_BLOB_TYPE   = "RSAPRIVATEBLOB"
)
