package bcrypt

// Source: bcrypt.h
const (
	BCRYPT_MD5_ALGORITHM        = "MD5"
	BCRYPT_RNG_ALGORITHM        = "RNG"
	BCRYPT_SHA1_ALGORITHM       = "SHA1"
	BCRYPT_SHA256_ALGORITHM     = "SHA256"
	BCRYPT_SHA384_ALGORITHM     = "SHA384"
	BCRYPT_SHA512_ALGORITHM     = "SHA512"
	BCRYPT_ECDSA_P256_ALGORITHM = "ECDSA_P256"
	BCRYPT_ECDSA_P384_ALGORITHM = "ECDSA_P384"
	BCRYPT_ECDSA_P521_ALGORITHM = "ECDSA_P521"
)
