package bcrypt

// NTSTATUS WINAPI 	BCryptCloseAlgorithmProvider (BCRYPT_ALG_HANDLE, ULONG)

// NTSTATUS WINAPI 	BCryptCreateHash (BCRYPT_ALG_HANDLE, BCRYPT_HASH_HANDLE *, PUCHAR, ULONG, PUCHAR, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptDecrypt (BCRYPT_KEY_HANDLE, PUCHAR, ULONG, VOID *, PUCHAR, ULONG, PUCHAR, ULONG, ULONG *, ULONG)

// NTSTATUS WINAPI 	BCryptDestroyHash (BCRYPT_HASH_HANDLE)

// NTSTATUS WINAPI 	BCryptDestroyKey (BCRYPT_KEY_HANDLE)

// NTSTATUS WINAPI 	BCryptEncrypt (BCRYPT_KEY_HANDLE, PUCHAR, ULONG, VOID *, PUCHAR, ULONG, PUCHAR, ULONG, ULONG *, ULONG)

// NTSTATUS WINAPI 	BCryptEnumAlgorithms (ULONG, ULONG *, BCRYPT_ALGORITHM_IDENTIFIER **, ULONG)

// NTSTATUS WINAPI 	BCryptFinishHash (BCRYPT_HASH_HANDLE, PUCHAR, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptGenerateSymmetricKey (BCRYPT_ALG_HANDLE, BCRYPT_KEY_HANDLE *, PUCHAR, ULONG, PUCHAR, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptGenRandom (BCRYPT_ALG_HANDLE, PUCHAR, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptGetFipsAlgorithmMode (BOOLEAN *)

// NTSTATUS WINAPI 	BCryptGetProperty (BCRYPT_HANDLE, LPCWSTR, PUCHAR, ULONG, ULONG *, ULONG)

// NTSTATUS WINAPI 	BCryptHash (BCRYPT_ALG_HANDLE, PUCHAR, ULONG, PUCHAR, ULONG, PUCHAR, ULONG)

// NTSTATUS WINAPI 	BCryptHashData (BCRYPT_HASH_HANDLE, PUCHAR, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptImportKeyPair (BCRYPT_ALG_HANDLE, BCRYPT_KEY_HANDLE, LPCWSTR, BCRYPT_KEY_HANDLE *, UCHAR *, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptOpenAlgorithmProvider (BCRYPT_ALG_HANDLE *, LPCWSTR, LPCWSTR, ULONG)

// NTSTATUS WINAPI 	BCryptSetProperty (BCRYPT_HANDLE, LPCWSTR, PUCHAR, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptDuplicateHash (BCRYPT_HASH_HANDLE, BCRYPT_HASH_HANDLE *, UCHAR *, ULONG, ULONG)

// NTSTATUS WINAPI 	BCryptVerifySignature (BCRYPT_KEY_HANDLE, void *, UCHAR *, ULONG, UCHAR *, ULONG, ULONG)
