package blob

// Source: bcrypt.h
const (
	BCRYPT_OPAQUE_KEY_BLOB   = "OpaqueKeyBlob"
	BCRYPT_KEY_DATA_BLOB     = "KeyDataBlob"
	BCRYPT_AES_WRAP_KEY_BLOB = "Rfc3565KeyWrapBlob"
	BCRYPT_ECCPUBLIC_BLOB    = "ECCPUBLICBLOB"
	BCRYPT_ECCPRIVATE_BLOB   = "ECCPRIVATEBLOB"
	BCRYPT_RSAPUBLIC_BLOB    = "RSAPUBLICBLOB"
	BCRYPT_RSAPRIVATE_BLOB   = "RSAPRIVATEBLOB"
)
