package blob

// Source: bcrypt.h
const (
	BCRYPT_OPAQUE_KEY_BLOB_STRING   = "OpaqueKeyBlob"
	BCRYPT_KEY_DATA_BLOB_STRING     = "KeyDataBlob"
	BCRYPT_AES_WRAP_KEY_BLOB_STRING = "Rfc3565KeyWrapBlob"
	BCRYPT_ECCPUBLIC_BLOB_STRING    = "ECCPUBLICBLOB"
	BCRYPT_ECCPRIVATE_BLOB_STRING   = "ECCPRIVATEBLOB"
	BCRYPT_RSAPUBLIC_BLOB_STRING    = "RSAPUBLICBLOB"
	BCRYPT_RSAPRIVATE_BLOB_STRING   = "RSAPRIVATEBLOB"
)
